Add --dryRun option
nim-lang/nimble pull request #964
Opened 2021-12-10 15:27 UTC by CyberTailor

I'm not able to test this because nimble fails to build (`tools.nim(11, 14) Error: cannot open file: compiler/nimblecmd`) even with Nim compiled from devel branch, so testing is required.

This PR closes issue #261

2021-12-14 12:51 UTC, dom96 requested changes
This looks good, but I fear it will be quite fragile. It's unclear which procs handle `dryRun` and which don't. For example you have `setupNimbleConfig` handling it, but then below where it's called you see another check for `dryRun`. This means we might end up with `dryRun` not being correctly handled in the future because someone not familiar with the code forgets to use it, or uses it more than necessary.

It's definitely non-trivial to make this safer though unfortunately. The only thing I can think of is to create Nimble-specific wrappers for all procs that write/remove/etc files and execute commands. Tbh maybe we should do this? We already have `doCmd`.

My other concern is that we will see messages the imply actions were taken, even with the `dryRun`. We need to make it clear that they weren't taken.

2021-12-14 12:51 UTC, dom96 commented on tests/tuninstall.nim
> +
Does this test to verify that a package wasn't uninstalled due to the `--dryRun`? Maybe I'm missing it but I don't see it. Please call out the part of this test that tests for this with a comment in the code.

2021-12-14 12:51 UTC, dom96 commented on src/nimblepkg/nimscriptexecutor.nim
> +    raise nimbleQuit(QuitFailure)
Doesn't `writeHelp` already raise?

2021-12-14 12:51 UTC, dom96 commented on src/nimble.nim
>      displayInfo(&"\"{nimbleConfigFileName}\" is set up.")
seeing this with `--dryRun` would be quite confusing

2021-12-14 12:51 UTC, dom96 commented on src/nimble.nim
>    displayInfo(&"\"{nimblePathsFileName}\" is {action}.")
this will seem confusing with --dryRun

2023-04-14 11:37 UTC, CyberTailor commented
Closing as this implementation is too fragile

2023-04-14 11:37 UTC, closed without merging